modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="spears"
version="2.0.0"
displayName="Spears"
displayURL="https://modrinth.com/mod/spears-mod"
credits="Created with MCreator barebone and maintained by Titan1um"
authors="Polr, Titan1um"
description='''
Adds spears in versions before their addition to the game!
'''

[[dependencies.spears]]
    modId="neoforge"
    type="required"
    versionRange="[21.8.31,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.spears]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.8]"
    ordering="AFTER"
    side="BOTH"
